In [27]:
from seq2seq_tf2.batcher import batcher, Vocab

In [28]:
params={'vocab_path':'../Word2Vec/week1-homework/datasets/vocab.txt',
        'vocab_size':30000,
        'train_seg_x_dir':'../Word2Vec/week1-homework/datasets/train_set.seg_x.txt',
        'train_seg_y_dir':'../Word2Vec/week1-homework/datasets/train_set.seg_y.txt',
        'test_seg_x_dir':'../Word2Vec/week1-homework/datasets/test_set.seg_x.txt',
        'max_enc_len':200,
        'max_dec_len':40,
        'batch_size':256,
        'mode':'train',
       }

In [29]:
vocab = Vocab(params["vocab_path"], params["vocab_size"])
print('true vocab is ', vocab)

max_size of vocab was specified as 30000; we now have 30000 words. Stopping reading.
Finished constructing vocabulary of 30000 total words. Last word added: 肝病毒属
true vocab is  <seq2seq_tf2.batcher.Vocab object at 0x63647da50>


In [30]:
print("Creating the batcher ...")
b = batcher(vocab, params)

Creating the batcher ...


In [34]:
for batch in b:
    print(batch)
    break

({'enc_input': <tf.Tensor: shape=(256, 200), dtype=int32, numpy=
array([[  479,  1199,     4, ...,     1,     1,     1],
       [ 1017,     0,   513, ...,     1,     1,     1],
       [ 1777,   203,   643, ...,   528,  1109,  1771],
       ...,
       [11079,   643, 18126, ...,     1,     1,     1],
       [ 1794,   154,  2391, ...,    19,    24,   234],
       [ 1911,  2021,  1245, ...,     1,     1,     1]], dtype=int32)>, 'extended_enc_input': <tf.Tensor: shape=(256, 200), dtype=int32, numpy=
array([[  479,  1199,     4, ...,     1,     1,     1],
       [ 1017, 30000,   513, ...,     1,     1,     1],
       [ 1777,   203,   643, ...,   528,  1109,  1771],
       ...,
       [11079,   643, 18126, ...,     1,     1,     1],
       [ 1794,   154,  2391, ...,    19,    24,   234],
       [ 1911,  2021,  1245, ...,     1,     1,     1]], dtype=int32)>, 'article_oovs': <tf.Tensor: shape=(256, 7), dtype=string, numpy=
array([[b'\xe7\xb4\xaf\xe4\xba\xba', b'', b'', ..., b'', b'', b''],
  